import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Bot, Boxes, BrainCircuit, Cable, Cpu, Plug, Sparkles, TerminalSquare } from "lucide-react";
import { Footer } from "@/components/footer";
import { StatusBadge } from "@/components/status/status-badge";

export const metadata: Metadata = { title: "Integrations | ROSClaw", description: "Explore ROSClaw model providers, external agents, MCP interfaces, Skills, robot bodies, and simulation integrations.", alternates: { canonical: "/integrations" } };
const groups = [
  [BrainCircuit,"Model providers","Reasoning providers for the Native Agent. Provider choice does not change the physical authority boundary.",["OpenAI-compatible","Anthropic-compatible","Local / configured endpoints"],"Experimental"],
  [TerminalSquare,"External agents","Agent harnesses can use ROSClaw as the governed body boundary through project integration.",["Codex","Claude Code","OpenClaw workspace Skill"],"Developer Observed"],
  [Plug,"Hardware MCPs","Typed interfaces expose sensors, bodies, tools, and devices. Each listing remains source-linked.",["ROS 2","RealSense","Industrial + lab devices"],"Indexed"],
  [Sparkles,"Skills","Reusable behavior and task knowledge layered over interfaces and runtime policy.",["Navigation","Manipulation","Perception workflows"],"Indexed"],
  [Bot,"Robot bodies","Profiles and executors connect the governed runtime to a declared embodiment.",["UR5e simulation","RealSense components","Additional Alpha profiles"],"Component Tested"],
  [Boxes,"Simulation","Validate mission logic and evidence paths before enabling physical execution.",["MuJoCo","Digital-twin workflows","Offline receipt path"],"Simulation Verified"],
] as const;
export default function IntegrationsPage(){return <main className="min-h-screen bg-[#060809] pt-16"><section className="runtime-grid border-b border-white/[0.08] px-4 py-20 sm:px-6 md:py-28 lg:px-8"><div className="mx-auto max-w-[1440px]"><p className="section-kicker">Integration map</p><h1 className="mt-5 max-w-5xl text-balance text-4xl font-semibold tracking-[-0.05em] text-white sm:text-6xl">Bring the models and tools. Keep one governed body boundary.</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-white/52">ROSClaw connects cognitive providers, Agent harnesses, MCP interfaces, reusable Skills, simulation, and robot bodies without conflating integration with verification.</p></div></section><section className="px-4 py-20 sm:px-6 md:py-28 lg:px-8"><div className="mx-auto grid max-w-[1440px] gap-px border border-white/10 bg-white/10 md:grid-cols-2 lg:grid-cols-3">{groups.map(([Icon,title,body,items,status])=>{const C=Icon as typeof Cable;return <article key={title} className="bg-[#080b0c] p-7"><div className="flex items-start justify-between gap-4"><C className="h-5 w-5 text-cognitive-cyan"/><StatusBadge status={status}/></div><h2 className="mt-10 text-2xl font-semibold text-white">{title}</h2><p className="mt-3 text-sm leading-relaxed text-white/45">{body}</p><ul className="mt-6 space-y-2 border-t border-white/[0.08] pt-5 font-mono text-[10px] uppercase tracking-[0.08em] text-white/38">{items.map(item=><li key={item} className="flex gap-2"><span className="text-cognitive-cyan">+</span>{item}</li>)}</ul></article>})}</div></section><section className="border-y border-white/[0.08] bg-[#050708] px-4 py-20 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-[1440px] gap-8 lg:grid-cols-[0.7fr_1.3fr]"><div><Cpu className="h-6 w-6 text-physical-orange"/><h2 className="mt-6 text-3xl font-semibold text-white">Read status labels literally.</h2></div><p className="text-base leading-relaxed text-white/52">Indexed means discoverable. Component Tested means a component surface has test evidence. Simulation Verified means the published simulation path completed with evidence. None of these labels silently implies verified physical action. The exact evidence boundary remains visible on Status and detail pages.</p></div></section><section className="px-4 py-20 text-center sm:px-6"><h2 className="text-3xl font-semibold text-white">Start with MCP interfaces and Skills.</h2><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/hub/mcps" className="focus-ring inline-flex items-center justify-center gap-2 bg-cognitive-cyan px-6 py-3 font-semibold text-[#021012]">Browse MCPs <ArrowRight className="h-4 w-4"/></Link><Link href="/hub/skills" className="focus-ring inline-flex items-center justify-center gap-2 border border-white/15 px-6 py-3 text-sm text-white/70">Browse Skills <ArrowRight className="h-4 w-4"/></Link></div></section><Footer/></main>}
